version: '2.2'

services:
  cube:
    image: cubejs/cube:latest
    ports:
      - 4000:4000 # Cube.js api and Developer Playground
      - 3000:3000 # Dashboard app
    env_file: .env
    volumes:
      - .:/cube/conf
